title:        Getting Started
url:          http://getting-started.apievangelist.com
logo:         http://kinlane-productions.s3.amazonaws.com/api-evangelist/api-evangelist-logo-getting-started.png
logo_width:   80
logo_bottom_padding: 10
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 150
paginate_path: "/news/page:num/"

categories_path : /categories.html
tags_path : /tags.html

org: api-evangelist
repo: getting-started
resource: getting-started
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI

get_color: 009900
post_color: 0000ff
put_color: FF0080
delete_color: FF9900

# Masthead title
masthead_link: http://getting-started.apievangelist.com
masthead_font_size: 80
masthead_title: '{"Getting Started"}'

# Feature
feature_title: API Design Providers Guide
feature_link: http://apis.how/xzca4kr2wb
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/3scale/report-image-api-design.png
feature_image_width: 45

# Project
project_image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/building-blocks/bw-running.png
project_summary: A getting started page for APIs is all about getting the new and potential API consumer up to speed with what it takes to get started with an API. This is my research to track on the different approaches, and aggregate into a single approach I can apply to my own APIs, as well as share along the way.

# Navigation
navigation:
  - label1: Home
    link1: /
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 20
    decorate: 0
  - label1: News
    link1: /news/
    size1: 80
    extend: 1
    label2: RSS
    link2: /blog.xml
    size2: 60
    padding: 5
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 20
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 15
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json
